# Generated by `just build release` (scripts/build/homebrew.ts). Don't edit by hand.
class Statuz < Formula
  desc "Schedule and publish to X, Bluesky, Mastodon and LinkedIn from the terminal"
  homepage "https://statuz.app"
  version "2.0.1"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://cdn.statuz.app/download/cli/2.0.1/statuz-cli-darwin-arm64-2.0.1.tgz"
      sha256 "eebe0081d70e64189185e6c3bc763e844ea0efe75cc510aa0f4031c643d2f004"
    end
    on_intel do
      url "https://cdn.statuz.app/download/cli/2.0.1/statuz-cli-darwin-x64-2.0.1.tgz"
      sha256 "a462c1f069cac9f2c6e016f9c172f79d12c022c9caf012cb87ad9b6c67e2f475"
    end
  end

  on_linux do
    on_arm do
      url "https://cdn.statuz.app/download/cli/2.0.1/statuz-cli-linux-arm64-2.0.1.tgz"
      sha256 "c15f759a23818a5b3d4cd31ff228e70cdbf38b93a28684dbe55c4e4e32aa88d9"
    end
    on_intel do
      url "https://cdn.statuz.app/download/cli/2.0.1/statuz-cli-linux-x64-2.0.1.tgz"
      sha256 "e9949dba7713a33c5b1c73d1e48b3d4437b0f7567802dd17827bb385dac4c76a"
    end
  end

  def install
    bin.install "bin/statuz"
  end

  def caveats
    <<~EOS
      Get started:
        statuz init
        statuz accounts connect --platform bluesky
        statuz start
      The statuz-cli npm package installs the same binary.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/statuz --version")
  end
end
