# Generated by `just build release` (scripts/build/homebrew.ts). Don't edit by hand.
class Statuz < Formula
  desc "Schedule and publish to X, Bluesky, Mastodon and LinkedIn from the terminal"
  homepage "https://statuz.app"
  version "2.0.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://registry.npmjs.org/statuz-cli-darwin-arm64/-/statuz-cli-darwin-arm64-2.0.0.tgz"
      sha256 "d76b851abe3dfa80eb905a573e1b89d69dc779783f855d8c7f12e904cc97fc80"
    end
    on_intel do
      url "https://registry.npmjs.org/statuz-cli-darwin-x64/-/statuz-cli-darwin-x64-2.0.0.tgz"
      sha256 "f093e8f6b41c2156230cc6e2bcfa89ade3f756a41dd758012cd6feb6b067db98"
    end
  end

  on_linux do
    on_arm do
      url "https://registry.npmjs.org/statuz-cli-linux-arm64/-/statuz-cli-linux-arm64-2.0.0.tgz"
      sha256 "62ccb583567aaf9470ab430d39902811ceb1eeb0d86a7d2d73131bbc87b39406"
    end
    on_intel do
      url "https://registry.npmjs.org/statuz-cli-linux-x64/-/statuz-cli-linux-x64-2.0.0.tgz"
      sha256 "9c4f9c98e1fdcaa932a487afd479d276bc3686477157c6264bbea304f43fcdf2"
    end
  end

  def install
    bin.install "bin/statuz"
  end

  def caveats
    <<~EOS
      Get started:
        statuz init
        statuz accounts connect --platform bluesky
        statuz start
      The statuz-cli npm package installs the same binary.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/statuz --version")
  end
end
